psul_rmd_drupal_integration.settings:
  type: config_object
  label: 'PSU Libraries RMD Integration Settings'
  mapping:
    api_url:
      type: string
      label: 'API URL'
    api_key:
      type: string
      label: 'API Key'
    cache_ttl:
      type: integer
      label: 'Cache TTL'
    attached_content_type:
      type: string
      label: 'Attached Content Type'
    publications_display:
      type: sequence
      label: 'Publications Display'
      sequence:
        type: string
